---
- name: Install required packages for plugins
  apt:
    name:
      - autoconf
      - make
      - build-essential
      - libgd-dev
      - libc6
      - libapache2-mod-php
      - openssl
      - libssl-dev
      - unzip
      - apache2
      - php
      - libnet-snmp-perl
      - python3
      - python3-pip
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install passlib
  pip:
    name: passlib

- name: nagios directory
  file:
    path: ~/nagios
    state: directory

- name: Download Nagios Core
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0777
    owner: root
    group: root

- name: Compile and install Nagios Core
  shell: |
     cd ~/nagios/nagioscore-*
     sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
     sudo make all
     sudo make install-groups-users
     sudo usermod - a -G nagios apache
     sudo make install
     sudo make install-daemoninit
     sudo make install-commandmode
     sudo make install-config
     sudo make install-webconf
     sudo a2enmod rewrite
     sudo a2enmod cgi

