---
- name: Adding users to Nagios
  community.general.htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: user
    password: user

- name: start nagios
  service:
    name: nagios
    enabled: true
    state: restarted

- name: Enable and start httpd service
  service:
    name: httpd
    enabled: true
    state: restarted


